org: pucminas
app: aws-hello-world
service: aws-hello-world
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  environment:
      APP_ENV_VARIABLE: FOOBAR

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /
          method: post
